### ISSUE TITLE
Could not find components folder for source. Please check the source contains a 'components' or 'esphome/components' folder.

### ISSUE THREAD

**Issue by iMiMx** [bendikwa/esphome-igrill#23]
Possibly since upgrading to 2023.9.0 (I'm afraid I didn't check the status prior to upgrading) but I've started to see the below - when I try to update the iGrill node.

```
INFO ESPHome 2023.9.0
INFO Reading configuration /config/esphome/igrill-ble-gateway.yaml...
Failed config

external_components: [source /config/esphome/igrill-ble-gateway.yaml:2]
  - 
    Could not find components folder for source. Please check the source contains a 'components' or 'esphome/components' folder.
    source: github://bendikwa/esphome-igrill@v1.2
```

I can see a 'components' folder on the github repo, so maybe something changed in the requirements of this folder?  Scanning through the release notes for 2023.9.0 nothing immediately popped out to me.

Has anyone else seen this?  I did check the 'closed' issues and couldn't see anything - the source is certainly still there.  

```
external_components:
  - source: github://bendikwa/esphome-igrill@v1.2  

esphome:
  name: igrill-ble-gateway
  friendly_name: igrill-ble-gateway
```

iGrill device shows as 'offline' in the ESPHome add-on, but it is on the network and is ping-able from HA.

**Comment by iMiMx** [comment]
```
external_components:
  - source: 
      type: git
      url: https://github.com/bendikwa/esphome-igrill/
      ref: v1.2
```

The above seems to work, but the shorthand noted on the ESP wiki does not - not for me anyway, not any more/currently:

https://esphome.io/components/external_components.html#external-components

Presumed esphome bug, perhaps?  Although I couldn't see anything on their github issues page.  I don't currently have any other external sources.
