### ISSUE TITLE
Problem with unit of measurement

### ISSUE THREAD

**Issue by figorr** [bendikwa/esphome-igrill#25]
Hi,

I am quite new with ESPHome but the process seems to work ok. I was able to follow all the process and the board had been recognized and it is reading the values from the iGrill v2. The problem is that in the logs the unit of measurement is F (farenheit) instead C (Celsius). So, for instance is showing 18F when the iGrill is showing 18C.

I tried also editing the "unit_of_measurement" with unit_of_measurement: "°C", without luck. Is still showing F

```
esphome:
  name: igrill
  friendly_name: iGrill

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXXXXXXXXXXXXXXXXXXX"

ota:
  password: "XXXXXXXXXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Igrill Fallback Hotspot"
    password: "XXXXXXXXXXX"

captive_portal:

# iGrill External Components
external_components:
  - source: github://bendikwa/esphome-igrill@v1.2

# iGrill bluetooth listener
esp32_ble_tracker:
#igrill_ble_listener:

# iGrill setup
ble_client:
  - mac_address: XX:XX:XX:XX:XX:XX
    id: igrill_device
    on_connect:
      then:
        - binary_sensor.template.publish:
            id: igrill_connection_bin
            state: on
    on_disconnect:
      then:
        - binary_sensor.template.publish:
            id: igrill_connection_bin
            state: off

binary_sensor:
  - platform: template
    name: "iGrill estado"
    id: igrill_connection_bin
    device_class: connectivity
    entity_category: diagnostic

sensor:
  - platform: igrill
    ble_client_id: igrill_device
    update_interval: 30s # default
    battery_level:
      name: "iGrill batería"
    temperature_probe1:
      name: "iGrill sonda 1"
      unit_of_measurement: "°C"  
    temperature_probe2:
      name: "iGrill sonda 2"
      unit_of_measurement: "°C"
    temperature_probe3:
      name: "iGrill sonda 3"
      unit_of_measurement: "°C"
    temperature_probe4:
      name: "iGrill sonda 4"
      unit_of_measurement: "°C"

```
Is there something wrong in my yaml file?
