### ISSUE TITLE
Are older iDevices-branded monitors supported?

### ISSUE THREAD

**Issue by Sdub76** [bendikwa/esphome-igrill#29]
I have 3 iGrill devices (2 iGrill mini and one iGrill 2) that are iDevices branded before Weber bought them out.   I have the following YAML loaded into my ESPWROOM32 running the latest ESPHome.  When I power on the devices, they never appear to the BLE listener.  

They do however show as available to pair in the Weber app, so I know they're chirping

I'm new to the ESPHome platform, so maybe there's some other dumb mistake I'm making?

```
esphome:
  name: esphome-web-5e5a34
  friendly_name: ESPHome Kitchen
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

safe_mode:
  disabled: true
  
# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: "xxxxx"
  password: "xxxxxx"

captive_portal:
  
web_server:
  port: 80
  
external_components:
  - source: github://bendikwa/esphome-igrill@v1.2

esp32_ble_tracker:
  
igrill_ble_listener:

```

![image](https://github.com/user-attachments/assets/45db1b61-c881-46bf-a8d0-ca212a671c8e)
