### ISSUE TITLE
Problem with temperature values

### ISSUE THREAD

**Issue by FedericoOldrini** [bendikwa/esphome-igrill#31]
Hi, i have correctly setup the bt connection to my igrill v2 but the temeratures seems to be wrong. On my igrill device with 2/4 probes the igrill read 20° and 21° but in home assistant i have something like -6.11°C. 

The two unplugged probes show -17,78 °C

I used the exact configuration posted in this repository readme:

```
- platform: igrill
    ble_client_id: igrill_device
    update_interval: 30s # default
    battery_level:
      name: "IGrill battery"
    temperature_probe1:
      name: "IGrill temp probe 1"
    temperature_probe2:
      name: "IGrill temp probe 2"
    temperature_probe3:
      name: "IGrill temp probe 3"
    temperature_probe4:
      name: "IGrill temp probe 4"
```

thanks

**Comment by guyank** [comment]
I resolved this by adding the unit of measurement to each probe

```
sensor:
  - platform: igrill
    ble_client_id: igrill_v2
    update_interval: 30s # default
    send_value_when_unplugged: true # default
    unplugged_probe_value: 0 # default
    battery_level:
      name: "IGrill v2 battery"
    temperature_probe1:
      name: "IGrill v2 temp probe 1"
      unit_of_measurement: "°C"
    temperature_probe2:
      name: "IGrill v2 temp probe 2"
      unit_of_measurement: "°C"
    temperature_probe3:
      name: "IGrill v2 temp probe 3"
      unit_of_measurement: "°C"
    temperature_probe4:
      name: "IGrill v2 temp probe 4"
      unit_of_measurement: "°C"
```

**Comment by braham2019** [comment]
I have the same issue, but adding unit_of_measurement is not working for me. 

This is the logfile. The values recorded are actually in Centigrade, but home assistant converts them to Fahrenheit, resulting in the negative incorrect values. 

Is there not a way to avoid this ? 

As a matter of fact, the first time I flashed the ESP, it gave the correct values. When I unplugged it and plugged it in elsewhere, it gave me these wrong values.

`[19:29:59.526][C][template.binary_sensor:016]: Template Binary Sensor 'iGrill mini connection status'
[19:29:59.526][C][template.binary_sensor:019]:   Device Class: 'connectivity'
[19:29:59.526][C][igrill:015]:   Temperature 'IGrill Mini temp'
[19:29:59.526][C][igrill:015]:     State Class: 'measurement'
[19:29:59.526][C][igrill:015]:     Unit of Measurement: '°F'
[19:29:59.526][C][igrill:015]:     Accuracy Decimals: 1
[19:29:59.526][C][igrill:025]:     Device Class: 'temperature'
[19:29:59.541][C][igrill:015]:   Battery Level 'IGrill Mini battery'
[19:29:59.541][C][igrill:015]:     State Class: 'measurement'
[19:29:59.541][C][igrill:015]:     Unit of Measurement: '%'
[19:29:59.541][C][igrill:015]:     Accuracy Decimals: 0
[19:29:59.546][C][igrill:025]:     Device Class: 'battery'
[19:29:59.559][C][esp32_ble:567]: BLE:
[19:29:59.559][C][esp32_ble:567]:   MAC address: 7C:87:CE:F4:**:**
[19:29:59.559][C][esp32_ble:567]:   IO Capability: none
[19:29:59.565][C][esp32_ble_tracker:613]: BLE Tracker:
[19:29:59.578][C][esp32_ble_tracker:614]:   Scan Duration: 300 s
[19:29:59.578][C][esp32_ble_tracker:614]:   Scan Interval: 320.0 ms
[19:29:59.578][C][esp32_ble_tracker:614]:   Scan Window: 30.0 ms
[19:29:59.578][C][esp32_ble_tracker:614]:   Scan Type: ACTIVE
[19:29:59.578][C][esp32_ble_tracker:614]:   Continuous Scanning: YES
[19:29:59.578][C][esp32_ble_tracker:622]:   Scanner State: RUNNING
[19:29:59.639][C][esp32_ble_tracker:623]:   Connecting: 0, discovered: 0, disconnecting: 0
[19:29:59.641][C][ble_client:027]: BLE Client:
[19:29:59.641][C][esp32_ble_client:071]:   Address: 70:91:8F:9C:F6:22
[19:29:59.641][C][esp32_ble_client:071]:   Auto-Connect: TRUE
[19:29:59.641][C][esp32_ble_client:075]:   State: ESTABLISHED
[19:29:59.641][C][esphome.ota:093]: Over-The-Air updates:
[19:29:59.641][C][esphome.ota:093]:   Address: esphome-web-f499d8.local:3232
[19:29:59.641][C][esphome.ota:093]:   Version: 2
[19:29:59.641][C][safe_mode:018]: Safe Mode:
[19:29:59.641][C][safe_mode:018]:   Successful after: 60s
[19:29:59.641][C][safe_mode:018]:   Invoke after: 10 attempts
[19:29:59.641][C][safe_mode:018]:   Duration: 300s
[19:29:59.641][C][api:222]: Server:
[19:29:59.641][C][api:222]:   Address: esphome-web-f499d8.local:6053
[19:29:59.641][C][api:222]:   Listen backlog: 4
[19:29:59.641][C][api:222]:   Max connections: 8
[19:29:59.641][C][api:234]:   Noise encryption: NO
[19:29:59.641][C][mdns:179]: mDNS:
[19:29:59.641][C][mdns:179]:   Hostname: esphome-web-f499d8
[19:30:21.062][D][igrill:330]: Requesting read of all values
[19:30:21.144][D][esp32_ble_client:199]: [0] [70:91:8F:9C:F6:22] ESP_GATTC_READ_CHAR_EVT
[19:30:21.147][D][sensor:131]: 'IGrill Mini battery': Sending state 70.00000 % with 0 decimals of accuracy
[19:30:21.247][D][esp32_ble_client:199]: [0] [70:91:8F:9C:F6:22] ESP_GATTC_READ_CHAR_EVT
[19:30:21.247][D][sensor:131]: 'IGrill Mini temp': Sending state 19.00000 °F with 1 decimals of accuracy`

**Comment by braham2019** [comment]
I asked my friend Chat for help, and he fixed it using a template that actually uses the same data but changes the unit of measurement

```
sensor:
  - platform: igrill
    ble_client_id: igrill_mini
    update_interval: 30s
    send_value_when_unplugged: true
    unplugged_probe_value: 0

    temperature_probe1:
      name: "IGrill Mini Temp Raw"
      id: igrill_temp_raw
      device_class: temperature
      unit_of_measurement: "°F"
      accuracy_decimals: 1

  - platform: template
    name: "IGrill Mini Temp (°C)"
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    lambda: |-
      return id(igrill_temp_raw).state;
    update_interval: 30s

```
